### ISSUE TITLE
Connections without SSL fail

### ISSUE THREAD

**Issue by fsp22** [tochev/python3-pcloudapi#1]
If I create a connection with _use_flag = false_, the code raises an exception.

The line of code to fix is:

```
 #utils.py:111
 match_hostname(sock.getpeercert(), server)
```

Adding an if statement resolve the issue. So

```
...
if use_ssl:
    sock = context.wrap_socket(sock, server_hostname=server)
sock.connect(sa)
if use_ssl:
    match_hostname(sock.getpeercert(), server)
return sock
...
```

**Comment by tochev** [comment]
Thanks, although I would strongly advice against using it without SSL

**Comment by fsp22** [comment]
you are right, but in some cases there is no choice (i.e. very old devices)
